New geospatial
CDCgov/phdi-sdk pull request #2
Opened 2022-07-27 13:11 UTC by bamader

This changeset introduces the new SDK geospatial functionality for both raw data and fhir formatted data in accordance with the SDK PRD and SDD. GeocodeResult has been defined as a dataclass, and an abstract base class GeocodeClient has been created for each of raw and FHIR-formatted data, from which vendor-specific implementations will derive. Users are now able to geocode from strings and dictionaries (in the case of raw data) and from resources and bundles (in the case of FHIR data). Unit tests are written for every function in all new modules.

Notes:
* because `fhir` was a taken name in the directory namespace, I've temporarily called the fhir directory `fhir_wrappers`; this can change once we move everything over to the new repo
* I know the new repo is created but wasn't sure if we were ready to begin pushing code to it yet (since there's so many dependencies and things to set up in the new repo), hence this PR being opened here

2022-07-28 00:29 UTC, KennethSkylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        rtype = resource.get("resourceType", "")
Could we change `rtype` to just `resource_type`? Makes it more readable

2022-07-28 00:29 UTC, KennethSkylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +    def geocode_resource(self, resource: dict, overwrite=True) -> dict:
Not a request for change just a small rant. I get annoyed when we have to name functions with words that are verbs and nouns at the same time lol.

2022-07-28 00:29 UTC, KennethSkylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        return resource
I think we should include what a function returns in the docstrings. Data type and what is it. Thoughts?

2022-07-28 12:30 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        rtype = resource.get("resourceType", "")
Sure thing!

2022-07-28 12:31 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +    def geocode_resource(self, resource: dict, overwrite=True) -> dict:
LOL I totally get it, I'm a language nerd myself so I can def see how that would be annoying. I'll try to think of another name but unfortunately I think `geocode_resource` is the most concise and precise summation of what the function does 😂

2022-07-28 12:33 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        return resource
I'm actually completely in agreement with you. When I took on a big codebase refactor a two months ago, having returns and return types in doc strings was one of the things I standardized. However, I then went out on vacation and came back to find them removed from all the docstrings, so some kind of decision had taken place while I was gone that docstrings didn't need returns or return data types. Maybe @spencer-skylight can provide more clarity around this, because I personally think a docstring _should_ have return information. Since we're in control of the SDK, I guess we can always add them back, too?

2022-07-28 13:00 UTC, spencer-skylight requested changes
Great work - this is exciting! I had a few comments to review, and also wanted to suggest trying to move the old `fhir.py` to phdi/fhir/__init__.py while we work on migrating to the new package structure.  I think the two are equivalent, and we will thank ourselves for not having to change everything from phdi.fhir_wrapper to phdi.fhir at the end of the refactor work.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +    which can be accessed using .client().
Rather than highlighing the use of the client (which is mostly meant to be internal), maybe replace this with:
```
Callers should use the interface methods (e.g. geocode_resource) to interact with the vendor-specific client property.
```

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +    def client(self):
I think we should comment each abstract class, not so much for SDK users, but for developer users who want to implement the methods and want to know what they should do.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        return resource
I agree that we should document what is returned. Currently our wider solution doesn't explicitly call out return value in the comments. I think this decision was made deliberately, with the expectation that the return value should be specified in the comments, and the return type is in the method signature.

I'd propose being more explicit in the comments about this returning a dict with the `resource` param enhanced with lat and long.  Maybe also discuss with the wider team why we are doing things this way currently and get a consensus around explicitly documenting return value or not.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +def _get_one_line_address(address: dict) -> str:
I'm a little torn on how to handle these, but what do you think about adding these to the abstract class definition itself?  I think that would allow extending classes to call them directly without needing to import an _-function explicitly.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +from abc import ABC, abstractmethod
I'm thinking we could move this to the `__init__.py` class, which would change import from:
```
import phdi.fhir.geospatial.geospatial
import phdi.fhir.geospatial.smarty
```
to
```
import phdi.fhir.geospatial
import phdi.fhir.geospatial.smarty
```

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +class SmartyGeocodeClient(FhirGeocodeClient):
I think this should be called SmartyFhirGeocodeClient to differentiate it from the one in phdi.geospatial.smarty.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        self.__client = (
I had thought we'd have the FhirGeocodeClient contain an instance of GeocodeClient rather than the vendor-specific implementation's client. That way you have access to GeocodeClient.geocode_from_string and geocode_from_dict.

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +            _ = self.geocode_resource(resource.get("resource", {}), overwrite=True)
Since the hierarchy of a bundle is `bundle -> entry (array) -> resource`, could we slightly refactor to rename `resource` to `entry`?

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/geospatial/smarty.py
> +            zip: the postal code to use
Since the aims for conversion to the SDK include equity and accessibility, I think we should support as many address fields as we can... Could we rename zip -> postal code (foreign addresses and maybe territories might not have "zip"?), and add other things that might be supported by fhir and/or geocode vendor services (district, country)?

2022-07-28 13:00 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/geospatial/smarty.py
> +            .with_licenses(["us-standard-cloud"])
The license should probably be a parameter, and I get a little nervous that we are only supporting a small subset of configuration that could be applied to a Smarty client (just a general rumination, not actionable yet).

2022-07-28 17:48 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +    def client(self):
Sure, I can do this

2022-07-28 18:05 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +def _get_one_line_address(address: dict) -> str:
I think that makes sense for both of these functions, since they exist to help facilitate processing FHIR data. I'll go ahead and fold them into the abstract class.

2022-07-28 18:12 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +def _get_one_line_address(address: dict) -> str:
I think they'll have to become static methods but that actually makes a lot of sense given the way we're using them--they don't care about class state at all and only operate on parameters in a utilitarian fashion so they can be bound to the class rather than specific objects.

2022-07-28 18:12 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +class SmartyGeocodeClient(FhirGeocodeClient):
Oh yeah, this is a good call

2022-07-28 18:14 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +from abc import ABC, abstractmethod
Should we do this for both sets of abstract classes? I.e. the fhir wrapper and the raw data one?

2022-07-28 18:15 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        self.__client = (
Ah I see. That makes sense to me, there's not really a reason to re-create client logic here.

2022-07-28 18:19 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/smarty.py
> +        self.__client = (
Also lets me refactor a bit of duplicated logic out

2022-07-28 18:25 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/geospatial/smarty.py
> +            zip: the postal code to use
Sure, I can add as many of those as I can

2022-07-28 18:29 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/geospatial/smarty.py
> +            zip: the postal code to use
Turns out smarty only supports one more parameter (though it's an important one for Puerto Rican addresses) so we'll have to be conscious of that when implementing new vendor options

2022-07-28 18:30 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/geospatial/smarty.py
> +            .with_licenses(["us-standard-cloud"])
That's fair. I'll make the license parameterized, but for now I think let's err on the side of presenting that small configuration. If a user doesn't have a preexisting geocoding vendor license, they're going to default to smarty, so I say let's try to make it as simple on them as possible.

2022-07-28 18:31 UTC, spencer-skylight commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +from abc import ABC, abstractmethod
Yeah, I think so, and we can use the same methodology as we develop the other modules as well.

2022-07-28 18:45 UTC, bamader commented on src/lib/phdi-building-blocks/phdi_building_blocks/fhir_wrappers/geospatial/geospatial.py
> +from abc import ABC, abstractmethod
That makes sense. And I like the way that cleans up both the directory structure and the imports.

2022-07-28 20:23 UTC, spencer-skylight requested changes

2022-07-28 20:23 UTC, spencer-skylight commented on phdi/geospatial/__init__.py
> +    def geocode_from_str(self, address: str) -> Union[GeocodeResult, None]:
Can of worms warning... Would there ever be a need to return more than one result, like if there was an ambiguous match?

2022-07-28 20:23 UTC, spencer-skylight commented on phdi/geospatial/__init__.py
> +    zipcode: str
Update to postalcode?

2022-07-28 20:23 UTC, spencer-skylight commented on phdi/geospatial/smarty.py
> +def _parse_smarty_result(lookup):
First off, I really like how you've modularlized this code! :rocket:  

And a nit: would this make more sense as a staticmethod?

2022-07-28 21:17 UTC, bamader commented on phdi/geospatial/smarty.py
> +def _parse_smarty_result(lookup):
Oooo good catch, yeah I definitely think it would. I'll fold it into the smarty client.

2022-07-28 21:18 UTC, bamader commented on phdi/geospatial/__init__.py
> +    zipcode: str
Whoops good catch

2022-07-28 21:29 UTC, bamader commented on phdi/fhir/geospatial/__init__.py
> +    def geocode_client(self):
To clarify, is your statement about getting rid of the abstract property geocode_client, or the whole abstract class for a GeocodeClient?

Re: whether all services have a client: my understanding is that this is actually a fairly common practice for most geolocating services. Things like the Census API and MapBox provide clients, as far as I know, and we saw the same pattern just with accessing an Azure storage container (we set up a client for connection purposes). Insofar as that's true, I do think having the abstract makes some sense until/unless we see that most vendors in question aren't providing a specific client property, though this isn't a strongly held conviction on my part.

Re: your second bullet on vendor-specific clients having different programming interfaces: actually having this set up as an abstract property in the base class is necessary for implementing classes to actually access and use it in a uniform way. Based on my reading and understanding, this is the standard way to create "instance variables" for abstract python classes (which aren't a thing on their own because there's no constructor). Now, I do see what your point is ostensibly saying, which is that there's no reason a vendor-specific class couldn't just define its own extra instance variable if it needs it, and if that is the point you're making, then I could probably be convinced to switch.

2022-07-28 21:31 UTC, bamader commented on phdi/geospatial/__init__.py
> +    def geocode_from_dict(self, address: dict) -> Union[GeocodeResult, None]:
Gotcha, I'll move the dictionary definition over to the abstract class. My worry with making it too FHIR-like is that if a user wants to use something FHIR-like, odds are they'll just import the fhir/geospatial module since we provide a perfect wrapper for a resource. If a user is making the conscious choice to geocode by generic dict rather than FHIR, I hesitate to impose too much in the way of an extension or nested entry structure just to access the address. And I think going really generic like this will help alleviate one of the concerns Jeremy voiced that users shouldn't have to provide too many parameters / should be able to supply whatever fields they have to geocode by address.

On the flip side, if your point is about using a FHIR-like structure in the sense that we can see what other geospatial fields FHIR supports and make those keys in the generic dict, that's something I could definitely get on board with, in which case just let me know!

2022-07-28 21:34 UTC, bamader commented on phdi/geospatial/__init__.py
> +    def geocode_from_str(self, address: str) -> Union[GeocodeResult, None]:
Ugh I thought a lot about this question when I was implementing it. What do we do if the geocoder returns multiple possible candidate matches... I personally settled on returning the first one for a couple of reasons:

1. it removes the hurdle of a user having to do filtering or post-processing to get a result they may just believe is simple. Trying to account for multiple matches means we'd have to do a lot more array formatting, which--while not necessarily bad--would make it more cumbersome to work with because the return data would always be _lists_ of GeocodeResults rather than just the desired result.
2. From what I found, SmartyStreets at least sorts the matches in the order of greatest likelihood, meaning that the first result is the one the geocoder considers "the best." I felt that for a dev release in particular, going with the single most likely result was good enough. I would hesitate to take on the additional burden of #1 above without having some user research or experimentation confirm for us that multiple matches is a problem users have.

2022-07-29 16:56 UTC, spencer-skylight commented on phdi/geospatial/__init__.py
> +    def geocode_from_str(self, address: str) -> Union[GeocodeResult, None]:
Sounds good.  I thought through this more, and think it's OK for a few reasons:
* This is a good and simple approach that STLTs might want to adopt at least as a starting point
* We can extend the function (i.e. return_all_results parameter) or create new functions later to return more data if it's deemed necessary

2022-07-29 17:03 UTC, spencer-skylight reviewed
One last remaining comment in phdi.geospatial.GeocodeClient for the geocode_from_dict function documentation - should contain the input format.  And related implementation in phdi.geospatial.smarty.SmartyGeocodeClient potentially updated to match documentation.

2022-08-01 16:05 UTC, merged